<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RepositoryUrl>https://github.com/BananaOnGitHub/PowerToysRun-PluginManager</RepositoryUrl>
    <Authors>BananaOnGitHub and contributors</Authors>
    <Version>0.4.0</Version>
  </PropertyGroup>
</Project>
